### ISSUE TITLE
Error when using dtdb.co

### ISSUE THREAD

**Issue by SnowballAntrobus** [haradan/NetrunnerImageLoader#1]
Using cards feed: http://dtdb.co/api/cards/
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@1ebdac86; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2486)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:801)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697)
	at uk.co.haradan.octgnimageloader.OCTGNImageLoader.readCardsByKeys(OCTGNImageLoader.java:220)
	at uk.co.haradan.octgnimageloader.OCTGNImageLoader.readCardsByKeys(OCTGNImageLoader.java:211)
	at uk.co.haradan.octgnimageloader.OCTGNImageLoader.doDownloadOctgnImages(OCTGNImageLoader.java:193)
	at uk.co.haradan.octgnimageloader.OCTGNImageLoader.downloadOctgnImages(OCTGNImageLoader.java:166)
	at uk.co.haradan.octgnimageloader.OCTGNImageLoaderUI$Worker.doInBackground(OCTGNImageLoaderUI.java:427)
	at uk.co.haradan.octgnimageloader.OCTGNImageLoaderUI$Worker.doInBackground(OCTGNImageLoaderUI.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by haradan** [comment]
This is fixed in v1.3.
